default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MyDatabase

test:
  <<: *default
  database: MyDatabase_Test

production:
  <<: *default
  database: MyDatabase_Production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>